version: "3.8"

services:
    nginx:
        image: nginx:1.23
        restart: always
        tty: true
        environment:
            APP_DIR: "/app"
        ports:
            - "172.1.13.1:80:80"
        volumes:
            - ".development/docker/nginx/templates:/etc/nginx/templates"
            - "./:/app"
        links:
            - php
        depends_on:
            - php
        networks:
            - app-network

    php:
        restart: always
        tty: true
        build:
            context: .
            dockerfile: .development/docker/php/Dockerfile
        command:
            - "/docker-entrypoint.sh"
        environment:
            XDEBUG_CONFIG: client_host=host.docker.internal
            PHP_IDE_CONFIG: "serverName=memebox"
            APP_DOMAIN: "meme.box"
        ports:
            - "172.1.13.1:9000:9000"
        volumes:
            - "./:/app"
            - ".development/docker/php/php.ini:/usr/local/etc/php/php.ini"
            - ".development/docker/php/docker-entrypoint.sh:/docker-entrypoint.sh"
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - app-network
        dns:
            - 8.8.8.8
        extra_hosts:
            - "host.docker.internal:host-gateway"

    postgres:
        image: postgres:16.1
        restart: always
        tty: true
        environment:
            POSTGRES_DB: memeboxdb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: Aa1234
        ports:
            - "172.1.13.1:5432:5432"
        volumes:
            - "wishlist-data:/var/lib/postgresql/data"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.1.13.0/24"
                  gateway: "172.1.13.1"

volumes:
    wishlist-data:
